### ISSUE TITLE
Plugin does not create a config.yml?

### ISSUE THREAD

**Issue by bloggy** [Govindass/skript-db#2]
Hi,
I found that the latest version of your plugin / addon does not create a config file. 1.2.1

**Comment by bloggy** [comment]
my fault (had not updated java)

**Comment by Govindass** [comment]
I should probably mention that it requires Java 11 now, it wasn't an intended change, it is just due to me having Java 11 on my computer, but I think it will be good as Java 8 shouldn't be used anymore

**Comment by bloggy** [comment]
No worries. It works flawless now! Thanks for maintaining this awesome addon!!!
