### ISSUE TITLE
How to get player's stats from table

### ISSUE THREAD

**Issue by Envqu** [Govindass/skript-db#3]
Hi, how can I get player's variable from table?

My table contains columns: `id | nick | level | xp`

`%{sql::level::1}%` showing me levels of player with id 1.
Can I do something like this? `%{sql::level::%player%}%`?
I want to set variable to level of player who joined to the server but %player% and %{_player}% (set to player's nickname)  sending `<none>`.

And I want to ask.. It is good idea to save 1000+ player's stats to variable in every 3 seconds?
Cause to refresh I must save that all again? It will not lag?

**Comment by Govindass** [comment]
you can loop the list variable and convert 1 to %player%, it is up to you how you implement the logic for it (it is definitely possible)

about saving a lot of stats to variable, it depends if you're using diskless variables or not, (!?-).* if not, that is a bad idea

**Comment by Govindass** [comment]
you may be able to think of something more efficient than saving 1000+ stats every 3 seconds, sounds like a bad design issue

**Comment by Envqu** [comment]
Diskless is temp variables? Like this: {_variable::*}?
In your opinion is better to save/load stats when player joins/leaves to server?
Then when he joins I need to load 1 value from table but its not possible? I must load whole table?

**Comment by Envqu** [comment]
Something like this is good?

![image](https://user-images.githubusercontent.com/70281617/113358413-0b35c880-9346-11eb-83a7-d89c33857c55.png)
