### ISSUE TITLE
Variable in UPDATE

### ISSUE THREAD

**Issue by Envqu** [Govindass/skript-db#4]
Hi.
Why Variables in Update not working?

It works:

execute "UPDATE `stats` SET `level` = %{_level}%, xp = %{_xp}% WHERE `nick` = 'Player123'" in {sql}

But not this:
execute "UPDATE `stats` SET `level` = %{_level}%, xp = %{_xp}% WHERE `nick` = %player's nickname%" in {sql}

I also tried:

set {_p} to player's nickname
and WHERE `nick` = %{_p}%" in {sql}

%player% gives error: "Parameter cannot be serialized: org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer

WHERE `nick` = '%{_p}%'" in {sql} gives error: Could not set parameter at position 3 (values was 'Player123')

**Comment by Govindass** [comment]
try name of player
